#!/bin/bash
#

set -e
set -o pipefail

export PATH=$PATH:$CRUNCH_SRC:$CRUNCH_SRC/crunch_scripts:$CRUNCH_SRC/crunch_scripts/bin:.
. <( arv-dax setup )

mntdir=`arv-dax keep`

jobparam=`arv-dax script_parameters`

verbose=`echo "$jobparam" | jq -r '.VERBOSE_FLAG'`

ifn=$mntdir/`echo "$jobparam" | jq -r '.INPUT_FILE'`
idb=$mntdir/`echo "$jobparam" | jq -r '.DATABASE_FILE'`
build=`echo "$jobparam" | jq -r '.GENOME_BUILD'`
#ofn=`echo "$jobparam" | jq -r '.OUTPUT_FILENAME'`
ofn="out-report.json"


if [ "$verbose" == "1" ]
then
  echo ">>>>>>>>>>>>>>>> ClinVarReport ifn '$ifn', idb '$idb', build '$build', ofn '$ofn'"
  echo "RUNNING: clinvar_report.py -c $idb -i $ifn -g $build -t json > $ofn"
fi

ucat="cat"
sfx=`echo "$ifn" | sed 's/.*\(vcf\|bz2\|gz\)$/\1/'`

if [[ "$sfx" == "gz" ]] ; then
  ucat="zcat"
elif [[ "$sfx" == "bz2" ]] ; then
  ucat="bzcat"
fi

#clinvar_report.py -c $idb -i $ifn -g $build -t json > $ofn
$ucat $ifn | vcfsrt -i - | clinvar_report.py -c $idb -g $build -t json > $ofn

arv-dax task finish
exit 0
